Remove HexMapTileOrientation operator int()
The `operator int()` method made `Variant(HexMapTileOrientation)`
ambiguous for MSVC.  The compiler couldn't determine if we wanted
`Variant(Variant &&)` or `Variant(int32_t)`.

```txt
<source>(87): error C2440: '<function-style-cast>': cannot convert from 'HexMapTileOrientation' to 'Variant'
<source>(87): note: 'Variant::Variant': ambiguous call to overloaded function
<source>(13): note: could be 'Variant::Variant(Variant &&)'
<source>(16): note: or       'Variant::Variant(int32_t)'
<source>(87): note: while trying to match the argument list '(HexMapTileOrientation)'
```

In this commit, I removed that operator.  It was unused; part of the
initial change from int-based orientation to a class.